FROM golang:1.26.4 AS builder
WORKDIR /app
COPY . .
RUN go generate ./...
RUN CGO_ENABLED=0 go build -ldflags="-installsuffix cgo" -o netledger-agent ./cmd/agent/main.go

FROM cgr.dev/chainguard/static
USER root
COPY --from=builder /app/netledger-agent /netledger-agent
ENTRYPOINT ["/netledger-agent"]
