FROM golang:1.26.4 AS builder
WORKDIR /app
COPY . .
RUN CGO_ENABLED=0 go build -ldflags="-installsuffix cgo" -o netledger-classifier ./cmd/classifier/main.go

FROM cgr.dev/chainguard/static
COPY --from=builder /app/netledger-classifier /netledger-classifier
ENTRYPOINT ["/netledger-classifier"]
