// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type NetLedgerConnVal struct {
	_             structs.HostLayout
	CgroupId      uint64
	SrcIp         uint32
	DstIp         uint32
	SrcPort       uint16
	DstPort       uint16
	Proto         uint8
	ConnDirection uint8
	_             [2]byte
	TxBytes       uint64
	RxBytes       uint64
	HaveSrc       uint8
	HaveDst       uint8
	_             [6]byte
}

// LoadNetLedger returns the embedded CollectionSpec for NetLedger.
func LoadNetLedger() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_NetLedgerBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load NetLedger: %w", err)
	}

	return spec, err
}

// LoadNetLedgerObjects loads NetLedger and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*NetLedgerObjects
//	*NetLedgerPrograms
//	*NetLedgerMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadNetLedgerObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadNetLedger()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// NetLedgerSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NetLedgerSpecs struct {
	NetLedgerProgramSpecs
	NetLedgerMapSpecs
	NetLedgerVariableSpecs
}

// NetLedgerProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NetLedgerProgramSpecs struct {
	CgBind4    *ebpf.ProgramSpec `ebpf:"cg_bind4"`
	CgConnect4 *ebpf.ProgramSpec `ebpf:"cg_connect4"`
	CgEgress   *ebpf.ProgramSpec `ebpf:"cg_egress"`
	CgIngress  *ebpf.ProgramSpec `ebpf:"cg_ingress"`
}

// NetLedgerMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NetLedgerMapSpecs struct {
	ConnMap *ebpf.MapSpec `ebpf:"conn_map"`
}

// NetLedgerVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NetLedgerVariableSpecs struct {
}

// NetLedgerObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadNetLedgerObjects or ebpf.CollectionSpec.LoadAndAssign.
type NetLedgerObjects struct {
	NetLedgerPrograms
	NetLedgerMaps
	NetLedgerVariables
}

func (o *NetLedgerObjects) Close() error {
	return _NetLedgerClose(
		&o.NetLedgerPrograms,
		&o.NetLedgerMaps,
	)
}

// NetLedgerMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadNetLedgerObjects or ebpf.CollectionSpec.LoadAndAssign.
type NetLedgerMaps struct {
	ConnMap *ebpf.Map `ebpf:"conn_map"`
}

func (m *NetLedgerMaps) Close() error {
	return _NetLedgerClose(
		m.ConnMap,
	)
}

// NetLedgerVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadNetLedgerObjects or ebpf.CollectionSpec.LoadAndAssign.
type NetLedgerVariables struct {
}

// NetLedgerPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadNetLedgerObjects or ebpf.CollectionSpec.LoadAndAssign.
type NetLedgerPrograms struct {
	CgBind4    *ebpf.Program `ebpf:"cg_bind4"`
	CgConnect4 *ebpf.Program `ebpf:"cg_connect4"`
	CgEgress   *ebpf.Program `ebpf:"cg_egress"`
	CgIngress  *ebpf.Program `ebpf:"cg_ingress"`
}

func (p *NetLedgerPrograms) Close() error {
	return _NetLedgerClose(
		p.CgBind4,
		p.CgConnect4,
		p.CgEgress,
		p.CgIngress,
	)
}

func _NetLedgerClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed netledger_bpfeb.o
var _NetLedgerBytes []byte
