// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type NetLedgerIpKey struct {
	_         structs.HostLayout
	CgroupId  uint64
	SrcIp     uint32
	DstIp     uint32
	SrcPort   uint16
	DstPort   uint16
	Direction uint8
	_         [3]byte
}

type NetLedgerIpValue struct {
	_          structs.HostLayout
	PacketSize uint64
}

// LoadNetLedger returns the embedded CollectionSpec for NetLedger.
func LoadNetLedger() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_NetLedgerBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load NetLedger: %w", err)
	}

	return spec, err
}

// LoadNetLedgerObjects loads NetLedger and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*NetLedgerObjects
//	*NetLedgerPrograms
//	*NetLedgerMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadNetLedgerObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadNetLedger()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// NetLedgerSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NetLedgerSpecs struct {
	NetLedgerProgramSpecs
	NetLedgerMapSpecs
	NetLedgerVariableSpecs
}

// NetLedgerProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NetLedgerProgramSpecs struct {
	EgressConnectionTracker    *ebpf.ProgramSpec `ebpf:"egress_connection_tracker"`
	EgressTcxConnectionTracker *ebpf.ProgramSpec `ebpf:"egress_tcx_connection_tracker"`
	IngressConnectionTracker   *ebpf.ProgramSpec `ebpf:"ingress_connection_tracker"`
}

// NetLedgerMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NetLedgerMapSpecs struct {
	IpMap *ebpf.MapSpec `ebpf:"ip_map"`
}

// NetLedgerVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NetLedgerVariableSpecs struct {
	ServiceSubnetMask   *ebpf.VariableSpec `ebpf:"service_subnet_mask"`
	ServiceSubnetPrefix *ebpf.VariableSpec `ebpf:"service_subnet_prefix"`
}

// NetLedgerObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadNetLedgerObjects or ebpf.CollectionSpec.LoadAndAssign.
type NetLedgerObjects struct {
	NetLedgerPrograms
	NetLedgerMaps
	NetLedgerVariables
}

func (o *NetLedgerObjects) Close() error {
	return _NetLedgerClose(
		&o.NetLedgerPrograms,
		&o.NetLedgerMaps,
	)
}

// NetLedgerMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadNetLedgerObjects or ebpf.CollectionSpec.LoadAndAssign.
type NetLedgerMaps struct {
	IpMap *ebpf.Map `ebpf:"ip_map"`
}

func (m *NetLedgerMaps) Close() error {
	return _NetLedgerClose(
		m.IpMap,
	)
}

// NetLedgerVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadNetLedgerObjects or ebpf.CollectionSpec.LoadAndAssign.
type NetLedgerVariables struct {
	ServiceSubnetMask   *ebpf.Variable `ebpf:"service_subnet_mask"`
	ServiceSubnetPrefix *ebpf.Variable `ebpf:"service_subnet_prefix"`
}

// NetLedgerPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadNetLedgerObjects or ebpf.CollectionSpec.LoadAndAssign.
type NetLedgerPrograms struct {
	EgressConnectionTracker    *ebpf.Program `ebpf:"egress_connection_tracker"`
	EgressTcxConnectionTracker *ebpf.Program `ebpf:"egress_tcx_connection_tracker"`
	IngressConnectionTracker   *ebpf.Program `ebpf:"ingress_connection_tracker"`
}

func (p *NetLedgerPrograms) Close() error {
	return _NetLedgerClose(
		p.EgressConnectionTracker,
		p.EgressTcxConnectionTracker,
		p.IngressConnectionTracker,
	)
}

func _NetLedgerClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed netledger_bpfel.o
var _NetLedgerBytes []byte
