// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type TestsEvent struct {
	_     structs.HostLayout
	Pid   uint32
	Saddr uint32
	Daddr uint32
	Sport uint16
	Dport uint16
	Comm  [16]int8
}

// LoadTests returns the embedded CollectionSpec for Tests.
func LoadTests() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TestsBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Tests: %w", err)
	}

	return spec, err
}

// LoadTestsObjects loads Tests and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*TestsObjects
//	*TestsPrograms
//	*TestsMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadTestsObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadTests()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// TestsSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TestsSpecs struct {
	TestsProgramSpecs
	TestsMapSpecs
	TestsVariableSpecs
}

// TestsProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TestsProgramSpecs struct {
	HandleTcpConnect *ebpf.ProgramSpec `ebpf:"handle_tcp_connect"`
}

// TestsMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TestsMapSpecs struct {
	Events *ebpf.MapSpec `ebpf:"events"`
}

// TestsVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TestsVariableSpecs struct {
}

// TestsObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadTestsObjects or ebpf.CollectionSpec.LoadAndAssign.
type TestsObjects struct {
	TestsPrograms
	TestsMaps
	TestsVariables
}

func (o *TestsObjects) Close() error {
	return _TestsClose(
		&o.TestsPrograms,
		&o.TestsMaps,
	)
}

// TestsMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadTestsObjects or ebpf.CollectionSpec.LoadAndAssign.
type TestsMaps struct {
	Events *ebpf.Map `ebpf:"events"`
}

func (m *TestsMaps) Close() error {
	return _TestsClose(
		m.Events,
	)
}

// TestsVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadTestsObjects or ebpf.CollectionSpec.LoadAndAssign.
type TestsVariables struct {
}

// TestsPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadTestsObjects or ebpf.CollectionSpec.LoadAndAssign.
type TestsPrograms struct {
	HandleTcpConnect *ebpf.Program `ebpf:"handle_tcp_connect"`
}

func (p *TestsPrograms) Close() error {
	return _TestsClose(
		p.HandleTcpConnect,
	)
}

func _TestsClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tests_bpfel.o
var _TestsBytes []byte
