// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package agent

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type netledgerIpKey struct {
	_         structs.HostLayout
	CgroupId  uint64
	SrcIp     uint32
	DstIp     uint32
	SrcPort   uint16
	DstPort   uint16
	Direction uint8
	_         [3]byte
}

type netledgerIpValue struct {
	_          structs.HostLayout
	PacketSize uint64
}

// loadNetledger returns the embedded CollectionSpec for netledger.
func loadNetledger() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_NetledgerBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load netledger: %w", err)
	}

	return spec, err
}

// loadNetledgerObjects loads netledger and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*netledgerObjects
//	*netledgerPrograms
//	*netledgerMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadNetledgerObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadNetledger()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// netledgerSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type netledgerSpecs struct {
	netledgerProgramSpecs
	netledgerMapSpecs
	netledgerVariableSpecs
}

// netledgerProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type netledgerProgramSpecs struct {
	EgressConnectionTracker    *ebpf.ProgramSpec `ebpf:"egress_connection_tracker"`
	EgressTcxConnectionTracker *ebpf.ProgramSpec `ebpf:"egress_tcx_connection_tracker"`
	IngressConnectionTracker   *ebpf.ProgramSpec `ebpf:"ingress_connection_tracker"`
}

// netledgerMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type netledgerMapSpecs struct {
	IpMap *ebpf.MapSpec `ebpf:"ip_map"`
}

// netledgerVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type netledgerVariableSpecs struct {
}

// netledgerObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadNetledgerObjects or ebpf.CollectionSpec.LoadAndAssign.
type netledgerObjects struct {
	netledgerPrograms
	netledgerMaps
	netledgerVariables
}

func (o *netledgerObjects) Close() error {
	return _NetledgerClose(
		&o.netledgerPrograms,
		&o.netledgerMaps,
	)
}

// netledgerMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadNetledgerObjects or ebpf.CollectionSpec.LoadAndAssign.
type netledgerMaps struct {
	IpMap *ebpf.Map `ebpf:"ip_map"`
}

func (m *netledgerMaps) Close() error {
	return _NetledgerClose(
		m.IpMap,
	)
}

// netledgerVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadNetledgerObjects or ebpf.CollectionSpec.LoadAndAssign.
type netledgerVariables struct {
}

// netledgerPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadNetledgerObjects or ebpf.CollectionSpec.LoadAndAssign.
type netledgerPrograms struct {
	EgressConnectionTracker    *ebpf.Program `ebpf:"egress_connection_tracker"`
	EgressTcxConnectionTracker *ebpf.Program `ebpf:"egress_tcx_connection_tracker"`
	IngressConnectionTracker   *ebpf.Program `ebpf:"ingress_connection_tracker"`
}

func (p *netledgerPrograms) Close() error {
	return _NetledgerClose(
		p.EgressConnectionTracker,
		p.EgressTcxConnectionTracker,
		p.IngressConnectionTracker,
	)
}

func _NetledgerClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed netledger_bpfeb.o
var _NetledgerBytes []byte
