name: Netledger CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.26.4

      - name: Install eBPF dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang llvm libbpf-dev linux-headers-$(uname -r)

      - name: Verify tools
        run: |
          which clang
          which llvm-strip
      
      - name: Build Agent
        run: |
          make build-agent

      - name: Run tests
        run: make test

      - name: Upload eBPF object
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: netledger_bpfel.o
          path: ./internal/agent/bpf/netledger_bpfel.o
          archive: false
  
  load-vm-amd64:
    runs-on: ubuntu-latest
    name: eBPF Load AMD Test
    needs: build
    strategy:
      fail-fast: false
      matrix:
        kernel:
          # https://quay.io/repository/lvh-images/kind?tab=tags
          - "6.6-20260603.072225-amd64"
          # - "6.1-20260603.042119-amd64" not supported
          # - "5.15-20260603.072225-amd64" # not supported
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - name: Download eBPF object
        uses: actions/download-artifact@70fc10c6e5e1ce46ad2ea6f2b72d43f7d47b13c3 # v8.0.0
        with:
          name: netledger_bpfel.o
          path: ./internal/agent/bpf/
      - name: Load NetLedger Agent in ${{ matrix.kernel }}
        uses: cilium/little-vm-helper@v0.0.30
        with:
          test-name: load-netledger
          image: "kind"
          image-version: ${{ matrix.kernel }}
          host-mount: ${{ github.workspace }}
          install-dependencies: "true"
          ssh-connect-wait-timeout: "2"
          cmd: |
            set -euo pipefail

            # print kernel version
            echo "Kernel Version: "
            uname -a

            # goto where host is mounted
            echo ""
            cd /host
            ls -lah

            echo ""
            sudo bpftool prog loadall \
              ./internal/agent/bpf/netledger_bpfel.o \
              /sys/fs/bpf/netledger \
              2>&1 | tee /tmp/bpf-load.log

            sudo bpftool prog show

  load-vm-arm64:
    runs-on: ubuntu-latest
    name: eBPF ARM Load Test
    needs: build
    strategy:
      fail-fast: false
      matrix:
        kernel:
          - "6.6-20260603.072225"
          # - "5.15-20260603.072225" not supported
    steps:
      - uses: actions/checkout@v4
      - name: Download eBPF object
        uses: actions/download-artifact@70fc10c6e5e1ce46ad2ea6f2b72d43f7d47b13c3 # v8.0.0
        with:
          name: netledger_bpfel.o
          path: ./internal/agent/bpf/
      - name: Load NetLedger Agent in ${{ matrix.kernel }}-arm64
        uses: cilium/little-vm-helper@v0.0.30
        with:
          test-name: load-netledger
          image: "kind"
          arch: "arm64"
          cpu-kind: max
          image-version: ${{ matrix.kernel }}-arm64
          kernel-version: ${{ matrix.kernel }}
          host-mount: ${{ github.workspace }}
          install-dependencies: "true"
          ssh-connect-wait-timeout: "2"
          cmd: |
            set -euo pipefail

            # print kernel version
            echo "Kernel Version: "
            uname -a

            # goto where host is mounted
            echo ""
            cd /host
            ls -lah

            echo ""
            sudo bpftool prog loadall \
              ./internal/agent/bpf/netledger_bpfel.o \
              /sys/fs/bpf/netledger \
              2>&1 | tee /tmp/bpf-load.log

            sudo bpftool prog show

  image-push:
    runs-on: ubuntu-latest
    name: Image push
    needs: [build, load-vm-amd64, load-vm-arm64]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Load versions from file
        id: versions
        run: |
          echo "AGENT_VERSION=$(cat versions.json | jq -r '.agent')" >> $GITHUB_ENV
          echo "CLASSIFIER_VERSION=$(cat versions.json | jq -r '.classifier')" >> $GITHUB_ENV
          echo "REPO=ghcr.io/acll19/netledger" >> $GITHUB_ENV
      - name: Build & push images
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t ${{ env.REPO }}/netledger-agent:${{ env.AGENT_VERSION }} -f Dockerfile.agent --push .
          docker buildx build --platform linux/amd64,linux/arm64 -t ${{ env.REPO }}/netledger-classifier:${{ env.CLASSIFIER_VERSION }} -f Dockerfile.classifier --push .
