name: LVH Load
# source: https://h0x0er.github.io/blog/2025/06/21/ebpf-loading-in-different-kernels/#lvh-images

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        kernel:
          # https://quay.io/repository/lvh-images/kind?tab=tags
          - "6.6-20260603.072225-amd64"
          - "6.6-20260603.072225-arm64"
          - "5.15-20260603.072225-amd64"
          - "5.15-20260603.072225-arm64"
          - "5.10-20260603.072225-amd64"
          - "5.10-20260603.072225-arm64"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install LVH (Go)
        run: |
          set -euxo pipefail

          # install lvh CLI
          go install github.com/cilium/little-vm-helper/cmd/lvh@latest

          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

          lvh version || true

      - name: Pull image
        run: |
          lvh images pull \
            quay.io/lvh-images/kind:${{ matrix.kernel }} \
            --dir .

      - name: Start VM
        run: |
          lvh run \
            --image ./images/*.qcow2 \
            --host-mount "$PWD" \
            --daemonize \
            -p 2222:22

      - name: Load eBPF object
        run: |
          ssh -p 2222 \
            -o StrictHostKeyChecking=no \
            root@localhost \
            '
            mkdir -p /sys/fs/bpf/test
            bpftool prog loadall \
              /root/myprog.bpf.o \
              /sys/fs/bpf/test

            sudo bpftool prog show
            '
